Revert "Manage flatpaks via HM activation script"
This reverts commit 3b3e5dba0933dbdccce7ef35bbf4d615ee5ccb03.

Installing new flatpaks fails:
error: Failed to install dev.restfox.Restfox: Flatpak system operation Deploy not allowed for user